Hotel/Hotel/Controllers/HotelController.cs
using Hotel.DataAccess;
using Hotel.EntityFramework.Models;
using Hotel.IDataAccess;
using Hotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hotel.ViewModels;
using PagedList;
using Hotel.Utilities;
using Hotel.Common.Utilities;
using System.Web.Configuration;
using System.Web.Mvc.Html;

namespace Hotel.Controllers
{
    public class HotelController : Controller
    {
        private readonly HotelEntities _db = new HotelEntities();
        private IHotelDataAccess _hotelDA;
        private IHotelDataAccess HotelDA => _hotelDA ?? (_hotelDA = new HotelDataAccess());

        private string strHost
        {
            get
            {
                string strH = WebConfigurationManager.AppSettings["host"].ToString() + "/";
                return strH;
            }
        }

        // GET: Hotel

        //public ActionResult detail()
        //{
        //    return View();
        //}

        [HttpPost]
        public ActionResult Index(SearchViewModel searchViewModel, int? page = 1)
        {
            if (searchViewModel.TypeInput == 0)
            {
                searchViewModel.Keyword = _db.tbl_Hotel.Where(d => d.Id.ToString() == searchViewModel.ItemId)
                        .Select(d => d.HotelName).FirstOrDefault().convertToUnSign2();
                Session["SearchHotel"] = searchViewModel;
                string rewriteUrl = ("/khach-san/" + (searchViewModel.Keyword ?? "-") + "-v"
                    + searchViewModel.ItemId + ".aspx?" + searchViewModel.GetSEOFriendlyURL());
                return RedirectPermanent(rewriteUrl);
            }
            if (searchViewModel.TypeInput == 1 && !string.IsNullOrEmpty(searchViewModel.ItemId) && searchViewModel.ItemId != "Refresh")
            {
                searchViewModel.Keyword = _db.tbl_Province.Where(d => d.ProvinceId.ToString() == searchViewModel.ItemId)
                        .Select(d => d.ProvinceName).FirstOrDefault().convertToUnSign2();
                Session["SearchHotel"] = searchViewModel;
                string rewriteUrl = ("/khach-san/tp"+ searchViewModel.ItemId +"/khach-san-tai-" + (searchViewModel.Keyword ?? "-")
                    +".aspx?" + searchViewModel.GetSEOFriendlyURL());
                return RedirectPermanent(rewriteUrl);
            }

            return RedirectPermanent("/khach-san");
        }
        public ActionResult Index(SearchViewModel searchViewModel, string dateCheckIn, string dateCheckOut, int? page = 1)
        {
            try
            {
                int pageSize = 4;
                int pageNumber = (page ?? 1);

                if (searchViewModel.TypeInput == 0)
                {
                    searchViewModel.Keyword = _db.tbl_Hotel.Where(d => d.Id.ToString() == searchViewModel.ItemId)
                        .Select(d => d.HotelName).FirstOrDefault().convertToUnSign2();
                    Session["SearchHotel"] = searchViewModel;
                    string rewriteUrl = ("/khach-san/" + (searchViewModel.Keyword ?? "-") + "-v" 
                        + searchViewModel.ItemId + ".aspx?" + searchViewModel.GetSEOFriendlyURL());
                    return RedirectPermanent(rewriteUrl);
                    //Session["SearchHotel"] = searchViewModel;
                    //return RedirectToAction("Detail", searchViewModel);
                }


                var listDistrictForProvince = new int[100];

                ViewBag.ArrListRatingTypeStr = "";
                string[] arrListRatingTypeStr = { };

                ViewBag.ArrListPriceTypeStr = "";
                string[] arrListPriceTypeStr = { };

                ViewBag.ArrListServiceTypeStr = "";
                string[] arrListServiceTypeStr = { };

                ViewBag.ArrListConvenientTypeStr = "";
                string[] arrListConvenientTypeStr = { };

                SearchViewModel search = Session["SearchHotel"] as SearchViewModel;

                if (search == null)
                    search = new SearchViewModel();

                if (searchViewModel.TypeInputText != null)
                    search.TypeInputText = searchViewModel.TypeInputText;
                if (searchViewModel.Keyword != null)
                    search.Keyword = searchViewModel.Keyword;
                if (searchViewModel.StartDate != null)
                    search.StartDate = searchViewModel.StartDate;
                if (searchViewModel.EndDate != null)
                    search.EndDate = searchViewModel.EndDate;
                if (searchViewModel.NumberRoom != null)
                    search.NumberRoom = searchViewModel.NumberRoom;
                if (searchViewModel.NumberAdul != null)
                    search.NumberAdul = searchViewModel.NumberAdul;
                if (searchViewModel.NumberChildren != null)
                    search.NumberChildren = searchViewModel.NumberChildren;
                if (searchViewModel.PriceFrom != null)
                    search.PriceFrom = searchViewModel.PriceFrom;
                else
                    search.PriceFrom = searchViewModel.PriceFrom;
                if (searchViewModel.PriceTo != null)
                    search.PriceTo = searchViewModel.PriceTo;
                else
                    search.PriceTo = searchViewModel.PriceTo;
                if (searchViewModel.HotelPriceType != null)
                {
                    search.HotelPriceType = searchViewModel.HotelPriceType;
                    arrListPriceTypeStr = search.HotelPriceType.Split(',');
                    ViewBag.ArrListPriceTypeStr = arrListPriceTypeStr;
                }
                else
                {
                    search.HotelPriceType = searchViewModel.HotelPriceType;
                    ViewBag.ArrListPriceTypeStr = arrListPriceTypeStr;
                }


                if (searchViewModel.HotelRatingType != null)
                {
                    search.HotelRatingType = searchViewModel.HotelRatingType;
                    arrListRatingTypeStr = search.HotelRatingType.Split(',');
                    ViewBag.ArrListRatingTypeStr = arrListRatingTypeStr;
                }
                else
                {
                    search.HotelRatingType = searchViewModel.HotelRatingType;
                    //arrListRatingTypeStr = search.HotelRatingType.Split(',');
                    ViewBag.ArrListRatingTypeStr = arrListRatingTypeStr;
                }

                if (searchViewModel.HotelType != null)
                    search.HotelType = searchViewModel.HotelType;
                else
                    search.HotelType = searchViewModel.HotelType;
                if (searchViewModel.HotelServiceType != null)
                {
                    search.HotelServiceType = searchViewModel.HotelServiceType;
                    arrListServiceTypeStr = search.HotelServiceType.Split(',');
                    search.HotelServiceType = searchViewModel.HotelServiceType;
                }
                else
                {
                    search.HotelServiceType = searchViewModel.HotelServiceType;
                    search.HotelServiceType = searchViewModel.HotelServiceType;
                }

                if (searchViewModel.HotelConvenientType != null)
                {
                    search.HotelConvenientType = searchViewModel.HotelConvenientType;
                    arrListConvenientTypeStr = search.HotelConvenientType.Split(',');
                    search.HotelConvenientType = searchViewModel.HotelConvenientType;
                }
                else
                {
                    search.HotelConvenientType = searchViewModel.HotelConvenientType;
                    search.HotelConvenientType = searchViewModel.HotelConvenientType;
                }

                if (searchViewModel.HotelArea != null)
                    search.HotelArea = searchViewModel.HotelArea;
                else
                    search.HotelArea = searchViewModel.HotelArea;
                if (searchViewModel.OrderPrice != null)
                    search.OrderPrice = searchViewModel.OrderPrice;
                else
                    search.OrderPrice = searchViewModel.OrderPrice;
                if (searchViewModel.OrderRating != null)
                    search.OrderRating = searchViewModel.OrderRating;
                else
                    search.OrderRating = searchViewModel.OrderRating;



                if (searchViewModel.ItemId != null)
                {
                    if(searchViewModel.ItemId == "Resfresh")
                    {
                        search.TypeInput = searchViewModel.TypeInput;
                        search.ItemId = null;
                    }
                    else
                    {
                        search.TypeInput = searchViewModel.TypeInput;
                        search.ItemId = searchViewModel.ItemId;
                    }
                    
                }
                //else
                //{
                //    search.TypeInput = 1;
                //    search.ItemId = "50";
                //}

                if (search.TypeInput == 1 && search.ItemId != null)
                {
                    var idProvince = Int32.Parse(search.ItemId);
                    var nameHotelsSearch = _db.tbl_Province.Find(idProvince);
                    listDistrictForProvince = _db.tbl_District.Where(x => x.ProvinceId == nameHotelsSearch.ProvinceId).Select(x => x.DistrictId).ToArray();
                    ViewBag.NameHotelsSearch = nameHotelsSearch;
                }

                //HotelPriceType: Loại giá
                var hotelPriceType = _db.tbl_HotelPriceType.Where(x => x.IsDelete == false).ToList();
                var hotelPriceTypeViewModel = hotelPriceType.Select(s => new ViewModels.HotelPriceTypeViewModel()
                {
                    Id = s.Id,
                    PriceTypeName = s.PriceTypeName,

Hotel/Hotel/Views/Shared/_Breadcrumbs.cshtml
<!-- breadcrumb -->
<div class="container">
    <div class="row">
        <ul class="breadcrumbs__wrapper d-flex align-items-center" itemscope itemtype="http://schema.org/BreadcrumbList">
            @Html.Raw(ViewBag.Breadcrumbs)
        </ul>
    </div>
</div>

Hotel/Hotel/Views/Shared/_Footer.cshtml
<div class="footer">
    <!-- menu-footer -->
    <div class="bottom-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mg-bt-20 ">
                    <a class="logo" href="#">
                        <img class="img-responsive" src="~/Content/assets/images/logo-combo.png" width="150px" />
                    </a>
                </div>
                <div class="col-md-4">                    
                    @Html.Raw(Hotel.Utilities.Utility.GetContentValue("home-address-company"))
                </div>
                <div class="col-md-4">                    
                    @Html.Raw(Hotel.Utilities.Utility.GetContentValue("home-policy-footer"))
                </div>
                <div class="col-md-4">
                    @Html.Raw(Hotel.Utilities.Utility.GetContentValue("home-partner-info"))                    
                    <div class="footer-block">
                        <div class="app-btn-group mg-bt-15">                            
                        </div>
                    </div>
                    <div class="footer-block">
                        <div class="socail-group">
                            @*<h5 class="footer-title text-uppercase mg-bt-10">
                                Kết nối với hotcombo.vn
                            </h5>
                            <ul class="list-inline">
                                <li>
                                    <a href="https://www.facebook.com/mytour.vn/" target="_blank">
                                        <i class="fa fa-facebook-square"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://plus.google.com/+MytourVndulichtietkiem" target="_blank">
                                        <i class="fa fa-google-plus-square"></i>
                                    </a>
                                </li>
                                <li>
                                    <a href="https://www.instagram.com/mytour.vn/" target="_blank">
                                        <i class="fa fa-instagram"></i>
                                    </a>
                                </li>
                            </ul>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /bottom-footer -->
    </div>
</div>
<!-- /menu-footer -->

Hotel/Hotel/Views/Shared/_Header.cshtml
@{
    //var province = ViewBag.Province as List<tbl_Province>;
    var hotelSuggest = ViewBag.hotelSuggest as List<SearchHotelSuggestModel>;
    var search = ViewBag.Search as SearchViewModel;
    DateTime dateCheckIn = DateTime.Today.AddDays(1);
    DateTime dateCheckOut = DateTime.Now.AddDays(2);
    int roomNumber = 1;
    int personNumber = 1;
    if (search != null)
    {
        dateCheckIn = search.StartDate != null ? search.StartDate.Value : dateCheckIn;
        dateCheckOut = search.EndDate != null ? search.EndDate.Value : dateCheckOut;

        if (search.StartDate == null)
        {
            search.StartDate = dateCheckIn;
        }
        if (search.EndDate == null)
        {
            search.EndDate = dateCheckOut;
        }
        roomNumber = search.NumberRoom != null ? search.NumberRoom.Value : 1;
        personNumber = search.NumberAdul != null ? search.NumberAdul.Value : 1;
    }

}

<header class="header-desktop">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-2">
                <div class="logo navbar-brand">
                    <a href='@Url.Action("Index","Home")'>
                        <img src="~/Content/assets/images/logo-combo.png" alt="" class="img-responsive" width="250px">
                    </a>
                </div>
            </div>
            <div class="col-md-4">
                <nav class="nav-bar">
                    <div class="navbar-collapse" id="menu-collapse">
                        <ul class="navbar-nav main-menu">
                            <li class="nav-item">
                                <a href='@Url.Action("Index","Home")' class="nav-link">
                                    Trang chủ
                                </a>
                            </li>
                            <li class="nav-item">
                                @*<a href='@Url.Action("Index","Hotel", new { TypeInput = "1", ItemId = "50" })' class="nav-link">
                                        Khách sạn
                                    </a>*@
                                <a href='/khach-san' class="nav-link">
                                    Khách sạn
                                </a>
                            </li>
                            <li class="tour ">
                                <a href="@Url.Action("Index","TravelGuide")" class="nav-link">
                                    Cẩm nang du lịch
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
            <div class="col-md-6">
                <ul class="nav navbar-nav navbar-right">
                    <li class="icon-block working-time">
                        <div class="wrapper">
                            <div class="mytour-phone">
                                @Html.Raw(Hotel.Utilities.Utility.GetContentValue("header-phone-contact"))
                            </div>
                            <div class="flight-phone text-center">
                                @Html.Raw(Hotel.Utilities.Utility.GetContentValue("header-phone-contact-flight"))
                            </div>
                        </div>
                    </li>
                    @*<li class="icon-block feedback">
                            <a href="#" mytour-ext="ajax-modal" modal-name="modal-feed-back">
                                <i class="fal fa-comments"></i>
                            </a>
                        </li>
                        <li class="icon-block notification">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                               aria-expanded="false">
                                <i class="fal fa-bell"></i>
                                <span class="notification-alarm number-notification">1</span>
                            </a>
                            <ul class="dropdown-menu notification-list scroll-y-t ps ps--theme_default">
                                <li class="new notify-item unread" data-title='notify_invite'>
                                    <span class="notification-close" data-type="invite_item">
                                        <i class="fal fa-times" onclick="offNotify('off_noti_invite')"></i>
                                    </span>
                                    <a target="_blank" class="notification-content" href="invite-other.html">
                                        <i class="fal fa-gift"></i>
                                        <p><strong>Giới thiệu bạn mới - Thêm tiền đi chơi</strong></p>
                                        <span>Tham gia ngay!</span>
                                    </a>
                                </li>
                                <li class="alert-fh new notify-item" data-count-notify="1">
                                </li>
                            </ul>
                        </li>*@
                    @{
                        var customerLogin = (CustomerAccountViewModel)Session["CustomerLogin"];
                    }

                    <li class="icon-block dropdown account">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">
                            @if (customerLogin == null )
                            {
                                <i class="fal fa-user"> @(customerLogin != null ? customerLogin.CustomerName.Substring(0, customerLogin.CustomerName.Length > 24 ? 24 : customerLogin.CustomerName.Length) : "")</i>
                            }
                            else
                            {
                                <img src="@(customerLogin != null ? customerLogin.ImageUrl : "")" style="width:40px;height:40px" /> @(customerLogin != null ? customerLogin.CustomerName.Substring(0, customerLogin.CustomerName.Length > 20 ? 20 : customerLogin.CustomerName.Length) : "")
                            }
                        </a>
                        <ul class="dropdown-menu text-center">
                            @if (Session["CustomerLogin"] == null)
                                {
                                <li class="p_login btn-show-login dropdown-item">
                                    <a href="javascript:;"
                                       data-toggle="modal" data-target="#LoginModal">Đăng nhập</a>
                                </li>
                                <li class="p_login dropdown-item"><a href="@Url.Action("Register","AccountCustomer")">Đăng ký</a></li>
                            }
                            else
                            {
                                @*<li class="p_login dropdown-item"><a href="#">Thông tin tài khoản</a></li>*@
                                <li class="p_login dropdown-item"><a href="@Url.Action("ChangePassword","AccountCustomer")">Đổi mật khẩu</a></li>
                                <li class="p_login dropdown-item"><a href="@Url.Action("LogOut","AccountCustomer")">Đăng xuất</a></li>
                            }
                            @*<li>
                                    <a href="favorite-hotels.html" class="events-tracking dropdown-item"
                                       data-category="Menu" data-action="Item Click"
                                       data-label="Khách sạn yêu thích">Khách sạn yêu thích</a>
                                </li>*@
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

@{ Html.RenderAction("_HeaderMobile", "Home");}

<script src="~/Content/Autocomplete/chosen.jquery.js" type="text/javascript"></script>
<script src="~/Content/Autocomplete/prism.js" type="text/javascript" charset="utf-8"></script>
<script src="~/Content/Autocomplete/init.js" type="text/javascript" charset="utf-8"></script>

Hotel/Hotel/Views/Shared/_Layout.cshtml
@{ 
    int version = 0;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@(ViewBag.Title ?? "Đặt phòng khách sạn, hotel trực tuyến hàng đầu Việt Nam") | www.hotcombo.vn</title>
    <meta name="description"
          content="Hơn 5000 khách sạn, hotels trong và ngoài nước. Giá rẻ nhất và đánh giá thực chỉ có tại hotcombo.vn. Khuyến mãi giảm giá lên đến 70%. Hoàn Tiền Nếu Không Hài Lòng.">
    <meta name="keywords"
          content="dat phong khach san, đặt phòng khách sạn, dat phong khach san truc tuyen, đặt phòng khách sạn trực tuyến, dat phong resort, đặt phòng resort, dat phong resort truc tuyen, đặt phòng resort trực tuyến">
    <meta name="theme-color" content="#36c5f4" />
    <meta http-equiv="x-dns-prefetch-control" content="on">
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link href="~/Content/assets/css/style.css?v=@version" rel="stylesheet" type="text/css" />
    <link href="~/Content/assets/css/home.css?v=@version" rel="stylesheet" type="text/css" />
    <link href="~/Content/assets/css/vendor.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/assets/css/new-style.css" rel="stylesheet" type="text/css" />

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/Content/assets/css/all.min.css" />
    <link rel="stylesheet" href="~/Content/assets/js/hotel-datepicker/css/hotel-datepicker.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">

    @*Script*@
    @*<script src="~/Content/assets/js/index.js" type="text/javascript"></script>*@
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>*@
    <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>


    <script src="~/Content/assets/js/hotel-datepicker/js/fetcha.min.js"></script>
    <script src="~/Content/assets/js/hotel-datepicker/js/hotel-datepicker.js" type="text/javascript"></script>
    <script src="~/Content/SocialLogin.js?v=4" type="text/javascript"></script>
    <script src="https://apis.google.com/js/api:client.js"></script>
    <script src="~/Scripts/plugins/hotel.js?v=@version"></script>
    @*<script src="~/Content/assets/js/index.js?v=@version"></script>*@

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script src="~/Content/assets/js/hotel-datepicker/js/fetcha.min.js"></script>
    <script src="~/Content/assets/js/hotel-datepicker/js/hotel-datepicker.js" type="text/javascript"></script>*@
    @Scripts.Render("~/bundles/jqueryval")

</head>
<body class="page-home">
    @Html.Partial("_Header")

    <!--Fb like share-->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v11.0&appId=560141008439125&autoLogAppEvents=1" nonce="ybGt12km"></script>
    <!--Fb like share-->
    <!-- box commercial -->
    <div>
        <!-- nav-fixed-right -->
        <div class="nav-fixed-right device-mb-none">
            <a class="nav-fixed-right-item" data-container="body" data-toggle="tooltip" data-placement="left"
               data-original-title="Về đầu trang" id="back_to_top" onclick='$("html, body").animate({ scrollTop: 0 }, "slow");'><i class="fa fa-arrow-up"></i></a>
            <a class="nav-fixed-right-item" data-container="body" data-toggle="tooltip" data-placement="left"
               data-original-title="Về trang chủ" href="/"><i class="fa fa-home"></i></a>
        </div>
        <!-- nav-fixed-right -->
    </div>
    @RenderBody()
    <!-- box commercial -->
    @Html.Partial("_Footer")
    <!-- /menu-footer -->
    <!-- Modal -->
    @Html.Partial("../AccountCustomer/_LoginPopup")
    @Html.Partial("../AccountCustomer/_ForgotPasswordPopup")
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>
    @RenderSection("scripts", required: false)  

    @if (TempData["Alert"] != null)
    {
        <script>
            alert('@Html.Raw(TempData["Alert"].ToString())');
        </script>
    }
</body>
</html>