Hotel/Hotel/Areas/Admin/Controllers/RoomAvailableController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Custom.Security;
using Hotel.Models;
using System.Globalization;
using Hotel.Controllers;
using Hotel.EntityFramework.Models;
using Newtonsoft.Json;

namespace Hotel.Areas.Admin.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class RoomAvailableController : BaseController //Controller
    {
        private readonly HotelEntities _db = new HotelEntities();

        // GET: AdminHotel/RoomAvailable

        public ActionResult Create(string id = "")
        {

            Guid hotelId = Guid.Empty;
            Guid roomId = Guid.Empty;

            Guid.TryParse(id, out hotelId);

            this.LoadDropDownList(hotelId, roomId, 0);


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RoomPrice model)
        {
            if (ModelState.IsValid)
            {
                if (this.SaveRoomPriceSchedule(model))
                {
                    ViewBag.Status = "Success";
                }
                else
                {
                    ViewBag.Status = "Error";
                }
            }
            else
            {
                ViewBag.Status = "Error";
            }

            this.LoadDropDownList(model.HotelId, model.RoomId, 0);

            return View(model);
        }

        //[HttpGet]
        public ActionResult _GetCalendarData(Guid roomId, string dateFrom, string dateTo)
        {
            Session["RoomId"] = roomId;
            // Initialization.
            JsonResult result = new JsonResult();
            List<CalendarDataView> calendarDataList = new List<CalendarDataView>();
            try
            {
                // Loading.                
                if (string.IsNullOrEmpty(dateFrom))
                {
                    dateFrom = DateTime.Now.AddDays(-30).ToString("dd/MM/yyyy HH:mm:ss");
                }
                else
                {
                    dateFrom = dateFrom + " 00:00:00";
                }

                if (string.IsNullOrEmpty(dateTo))
                {
                    dateTo = DateTime.Now.AddDays(30).ToString("dd/MM/yyyy HH:mm:ss");
                }
                else
                {
                    dateTo = dateTo + " 23:59:59";
                }

                DateTime _dateFrom = DateTime.Parse(dateFrom);
                DateTime _dateTo = DateTime.Parse(dateTo);

                var products = _db.tbl_RoomPrice.Include(p => p.tbl_Room.tbl_Hotel)
                    .Where(
                        p => p.RoomId == roomId
                        //&& _dateFrom <= p.DateAvailable
                        //&& p.DateAvailable <= _dateTo
                        && p.IsDelete != true
                    ).ToList();

                if (products != null)
                {
                    foreach (var p in products)
                    {
                        string checkBox = "\n <label>Hoạt động</label> <input id='{0}' onchange=\"ChangeStatusPrice('{1}',this)\" style='cursor: pointer;' type='checkbox' {2} />  ";
                        var _title = "SL còn lại: " + p.AvailableRoom.ToString()
                                + "\nGiá : " + p.PriceContract.ToString("#,###")
                                + "\nGiá KM: " + p.PricePromotion?.ToString("#,###")
                                + string.Format(checkBox, p.Id.ToString(), p.Id.ToString(), (p.IsActive.Value == true ? "checked='checked'" : ""));

                        var _description = "";

                        if (p.RoomDate >= DateTime.Now.Date)
                        {
                            if (p.IsActive.Value)
                            {
                                calendarDataList.Add(new CalendarDataView
                                {
                                    title = MvcHtmlString.Create(_title).ToHtmlString(),
                                    description = _description,
                                    start = (DateTime)p.RoomDate,
                                    end = (DateTime)p.RoomDate,
                                    backgroundColor = "#0ab80a",
                                    borderColor = "#00b300"
                                });
                            }
                            else
                            {
                                calendarDataList.Add(new CalendarDataView
                                {
                                    title = MvcHtmlString.Create(_title).ToHtmlString(),
                                    description = _description,
                                    start = (DateTime)p.RoomDate,
                                    end = (DateTime)p.RoomDate,
                                    backgroundColor = "#ff1b1b",
                                    borderColor = "#00b300"
                                });
                            }
                        }
                        else
                        {
                            calendarDataList.Add(new CalendarDataView
                            {
                                title = _title,
                                description = _description,
                                start = (DateTime)p.RoomDate,
                                end = (DateTime)p.RoomDate,
                                backgroundColor = "#556655",
                                borderColor = "#00b300"
                            });
                        }
                    }
                }

                // Processing.
                result = this.Json(calendarDataList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Info
                Console.Write(ex);
                result = this.Json(calendarDataList, JsonRequestBehavior.AllowGet);

            }

            // Return info.
            return result;
        }

        public ActionResult _ChangeStatusPrice(Guid PriceId, bool Status)
        {
            var products = _db.tbl_RoomPrice.Include(p => p.tbl_Room.tbl_Hotel)
                    .FirstOrDefault(
                        p => p.Id == PriceId
                        && p.IsDelete != true
                    );

            if (products != null)
            {
                //Change Status
                products.IsActive = Status;
                products.UserUpdate = User.UserId;
                products.DateUpdate = DateTime.Now;
                _db.SaveChanges();
                return this.Json(new { id = 1, message = "Đã lưu điều chỉnh" }, JsonRequestBehavior.AllowGet);
            }
            return this.Json(new { id = 0, message = "Điều chỉnh không thành công" }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult _GetHotelRoom(Guid hotelId)
        {
            var roomList = _db.tbl_Room.Where(r => r.HotelId == hotelId && r.IsDelete != true).ToList().Select(d => new { d.Id, d.RoomName, d.HotelId });
            Session["HotelId"] = hotelId;
            return Json(roomList, JsonRequestBehavior.AllowGet);
        }

        protected bool SaveRoomPriceSchedule(RoomPrice product)
        {
            try
            {
                if (product.DateType == "DateFromTo")
                {
                    if (product.DateFrom != null && product.DateTo != null)
                    {
                        DateTime dateAvailableFrom = (DateTime)product.DateFrom;
                        DateTime dateAvailableTo = (DateTime)product.DateTo;
                        double roomPriceContract = product.PriceContract;
                        double roomPricePromotion = product.PricePromotion.Value;

                        if (dateAvailableFrom < DateTime.Now.Date)
                        {
                            dateAvailableFrom = DateTime.Now.Date;
                        }

                        for (DateTime date = dateAvailableFrom.Date; date <= dateAvailableTo.Date; date = date.AddDays(1.0))
                        {
                            SavePrice(product, date);
                        }

                        return true;
                    }
                }
                if (product.DateType == "DateSelect")
                {
                    foreach (var date in product.DateList.Split(','))
                    {
                        SavePrice(product, Convert.ToDateTime(date));
                    }
                    return true;
                }
            }
            catch (Exception ex)
            {
                return false;
            }
            return false;
        }

        protected void SavePrice(RoomPrice product, DateTime date)
        {
            var roomPriceExist = _db.tbl_RoomPrice.Where(p => p.RoomId == product.RoomId && p.RoomDate == date).SingleOrDefault();

            if (roomPriceExist != null)
            {
                //Exist roomPrice: update                          
                roomPriceExist.HotelPriceTypeId = (int)Parameters.HotelPriceType.GiaThuong; //product.HotelPriceTypeId;
                roomPriceExist.PriceContract = product.PriceContract;
                roomPriceExist.PricePromotion = product.PricePromotion;
                roomPriceExist.PercentPromotion = Convert.ToDouble(String.Format("{0:0.00}", ((product.PriceContract - product.PricePromotion) / product.PriceContract * 100)));
                roomPriceExist.AvailableRoom = product.AvailableRoom;
                roomPriceExist.IsActive = true;
                roomPriceExist.UserUpdate = User.UserId;
                roomPriceExist.DateUpdate = DateTime.Now;

                _db.Entry(roomPriceExist).State = EntityState.Modified;
            }
            else
            {
                //Not exist product: insert new

Hotel/Hotel/Areas/Admin/Views/RoomAvailable/Create.cshtml
@model RoomPrice

@{
    //var sllHotel = ViewBag.sllHotel as IEnumerable<SelectListItem>;
    var sllRoom = ViewBag.sllRoom as IEnumerable<SelectListItem>;
    var RoomPriceType = ViewBag.RoomPriceType as IEnumerable<SelectListItem>;

    List<SelectListItem> sllActive = new List<SelectListItem>{
        new SelectListItem { Text = "Không", Value = "False" },
        new SelectListItem { Text = "Có", Value = "True", Selected = true }
    };
    List<SelectListItem> selectDate = new List<SelectListItem>
{
        new SelectListItem{Text = "Từ ngày - Đến ngày", Value = "DateFromTo"},
        new SelectListItem{Text = "Chọn ngày", Value = "DateSelect"}
    };
}
@using (Html.BeginMultipartForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="container-fluid">
        <div class="box-header">
            <h3 class="box-title">Đăng phòng bán</h3>
        </div><!-- /.box-header -->
        <!-- general form elements -->
        <div class="box box-primary">
            @*<div class="box-body">*@
            <div class="col-md-3">
                @{
                    if (ViewBag.Status == "Success")
                    {
                        <div class="alert alert-success alert-dismissable" style="max-width: 500px;">
                            <i class="fa fa-check"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <b>Cập nhật thành công!</b>
                        </div>
                    }
                    else if (ViewBag.Status == "Error")
                    {
                        <div class="alert alert-danger alert-dismissable" style="max-width: 500px;">
                            <i class="fa fa-ban"></i>
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <b>Cập nhật bị lỗi!</b> @ViewBag.Message
                        </div>
                    }
                }
                @*<div class="form-group">
                        <label>Tỉnh thành</label>
                        @Html.DropDownList("ProvineId", (IEnumerable<SelectListItem>)sllProvince, new { @class = "form-control", @style = "width: 200px;" })
                    </div>*@

                <div class="form-group">
                    <label>Chọn khách sạn</label>
                    @Html.DropDownList("HotelId", null, "--- Chọn khách sạn ---", new { @class = "form-control chosen-select", @style = " max-width: 600px; ", @onchange = "LoadRoomHotel();" })
                </div>

                <div class="form-group">
                    <label>Chọn phòng</label>
                    @Html.DropDownList("RoomId", (IEnumerable<SelectListItem>)sllRoom, "--- Chọn phòng ---", new { @class = "form-control chosen-select", @style = " max-width: 600px; ", @onchange = "LoadRoomAvailableCalendar();" })

                </div>
                <div class="form-group">
                    <label>Tuỳ chọn ngày</label>
                    @Html.DropDownList("DateType", (IEnumerable<SelectListItem>)selectDate, new { @id = "selectDate", @class = "form-control chosen-select", @style = " max-width: 600px; ", @onchange = "ChangeSelectDate(this);" })

                </div>
                <div id="DateSelect" class="select-date">
                    <div class="form-group">
                        <label>Chọn các ngày</label>
                        @Html.TextBoxFor(model => model.DateList, new { @class = "form-control", @style = " max-width: 600px; ", @autocomplete = "off" })
                    </div>
                </div>
                <div id="DateFromTo" class="select-date">
                    <div class="form-group">
                        <label>Từ ngày</label>
                        @Html.TextBoxFor(model => model.DateFrom, new { @class = "form-control", @style = " max-width: 600px; ", @autocomplete = "off" })
                    </div>

                    <div class="form-group">
                        <label>Đến ngày</label>
                        @Html.TextBoxFor(model => model.DateTo, new { @class = "form-control", @style = " max-width: 600px;", @autocomplete = "off" })
                    </div>
                </div>
                @*<div class="form-group">
                        <label>Loại giá</label>
                        @Html.DropDownList("PriceTypeId", (IEnumerable<SelectListItem>)RoomPriceType, "--- Chọn ---", new { @class = "form-control", @style = " max-width: 600px;" })
                    </div>*@

                <div class="form-group">
                    <label>Giá phòng</label>
                    @Html.TextBoxFor(model => model.PriceContract, new { @class = "form-control", @style = " max-width: 600px; ", @onkeyup = "FormatAmount(this);" })
                </div>

                <div class="form-group">
                    <label>Giá phòng khuyến mại</label>
                    @Html.TextBoxFor(model => model.PricePromotion, new { @class = "form-control", @style = " max-width: 600px;", @onkeyup = "FormatAmount(this);" })
                </div>

                <div class="form-group">
                    <label>Số lượng</label>
                    @Html.TextBoxFor(model => model.AvailableRoom, new { @class = "form-control", @style = " max-width: 600px; ", @type = "number" })
                </div>

                @*<div class="form-group">
                        <label>Hoạt động?</label>
                        @Html.DropDownList("IsActived", (IEnumerable<SelectListItem>)sllActive, new { @class = "form-control", @style = "max-width: 600px; " })
                    </div>*@
                <div class="form-group">
                    <button type="submit" id="submit" class="btn btn-success"><i class="fa fa-save"></i>&nbsp;Lưu</button>

                    <a class="btn btn-default f-right" href="@Url.Action("Index","Hotels")">Danh sách KS</a>
                </div>
            </div>
            <div class="col-md-9">
                <!--calendar-->
                <h4>
                    <i class="fa fa-calendar"></i>
                    <strong><span id="roomAvailableId" style="color:#0000cc;">Room Available Calendar</span></strong>
                </h4>
                <div id="calendar"></div>
                <!--.calendar-->
            </div>
            @*</div>*@

            @*<div class="box-footer">

                </div>*@
        </div>
        <!-- /.box-footer -->
    </div>
}
<script src="~/Content/plugins/datepicker/locales/bootstrap-datepicker.vi.js"></script>
<script src="~/Content/plugins/datepicker/bootstrap-datepicker.js"></script>
<script src="~/Content/ThemeAdmin/js/FormatNumber.js?v=1"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $("#DateList").datepicker({
            autoclose: false,
            multidate: true,
            multidateSeparator: ',',
            format: 'dd/mm/yyyy',
            keyboardNavigation: true,
            language: 'vi',
            startDate: new Date(),
            todayBtn: true,
            todayHighlight: true,
        });

        $("#DateFrom").datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy',
            keyboardNavigation: true,
            language: 'vi',
            startDate: new Date(),
            todayBtn: true,
            todayHighlight: true,
        });

        $("#DateTo").datepicker({
            autoclose: true,
            format: 'dd/mm/yyyy',
            keyboardNavigation: true,
            language: 'vi',
            startDate: new Date(),
            todayBtn: true,
            todayHighlight: true,
        });
        //LoadRoomHotel();
        LoadRoomAvailableCalendar();

        $('.select-date').hide();
        $('#' + $('#selectDate').val()).show();
    });

    ///////////////////////////

    function LoadRoomHotel() {
        if ($("#HotelId").val() != '') {
            $.ajax({
                url: '@Url.Action("_GetHotelRoom", "RoomAvailable")',
                data: { hotelId: $("#HotelId").val() },
                success: function (result) {
                    if (result != '') {
                        $('#RoomId').empty();
                        $('#RoomId').append($('<option/>', { value: 0}).html('--- Chọn phòng ---'));
                        $.each(result, function (i, state) {
                            $('#RoomId').append($('<option/>', { value: state.Id }).html(state.RoomName));
                        });
                        $('#RoomId').trigger("chosen:updated");
                    } else {
                        ShowNotify('Có lỗi xảy ra, vui lòng kiểm tra lại dữ liệu.', 'danger', 'top');
                    }

                }
            });

            $('#calendar').fullCalendar('destroy');
        }
    }

    function LoadRoomAvailableCalendar() {
        document.getElementById('roomAvailableId').innerText = $("#HotelId option:selected").text() + ' >> ' + $("#RoomId option:selected").text();
        $('#calendar').fullCalendar('destroy');
        $('#calendar').fullCalendar({
            header:
            {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            buttonText: {
                today: 'today',
                month: 'month',
                week: 'week',
                day: 'day'
            },

            events: function (start, end, timezone, callback) {
                if ($("#RoomId").val() > '0' || $("#RoomId").val() != '') {
                    $.ajax({
                        url: '/RoomAvailable/_GetCalendarData',
                        //type: "GET",
                        type: "POST",
                        dataType: "JSON",
                        data: {
                            "roomId": $("#RoomId").val(),
                            "dateFrom": $("#DateFrom").val(),
                            "dateTo": $("#DateTo").val()
                        },
                        success: function (result) {
                            var events = [];

                            $.each(result, function (i, data) {
                                events.push(
                                    {
                                        title: data.title,
                                        //description: data.description,
                                        start: moment(data.start).format('YYYY-MM-DD'),
                                        end: moment(data.end).format('YYYY-MM-DD'),
                                        backgroundColor: data.backgroundColor,
                                        borderColor: data.borderColor,
                                    });
                            });

                            callback(events);
                        }
                    });
                }
            },

            eventRender: function (event, element) {
                element.qtip(
                {
                    content: event.description
                });
            },

            editable: false
        });

    }

    function ChangeSelectDate(select) {
            $('.select-date').hide();
            $('#'+select.value).show();

    }

    function ChangeStatusPrice(priceId, checkBox) {
        event.preventDefault();
        if (!confirm("Xác nhận thay đổi trạng thái giá?")) {
            checkBox.checked = !checkBox.checked;
            return false;
        }
        $.ajax({
            url: '@Url.Action("_ChangeStatusPrice","RoomAvailable")',
            type: "GET",
            //type: "POST",
            dataType: "JSON",
            beforeSend: function () {
                $('#preloader-wrapper').toggleClass('hide');
            },
            data: {
                PriceId: priceId,
                Status: checkBox.checked
            },
            success: function (result) {
                $('#preloader-wrapper').toggleClass('hide');
                if (result.id == 1) {
                    ShowNotify(result.message, "success", "top");
                    LoadRoomAvailableCalendar();
                }
                else {
                    ShowNotify(result.message, "warning", "top");
                    checkBox.checked = !checkBox.checked;
                }
            },
            error: function () {
                $('#preloader-wrapper').toggleClass('hide');
                ShowNotify("Không thực hiện được", "danger", "top");
            }
            
        });

    }

    //Format Amount

    $(function () {
        $(document).ready(function () {
            FormatAmount(document.getElementById('PriceContract'));
            FormatAmount(document.getElementById('PricePromotion'));
        });
        $('#submit').on('click', function () {

            var priceContract = $('#PriceContract').val();
            $('#PriceContract').val(clearFormatNumber(priceContract));

            var pricePromotion = $('#PricePromotion').val();
            $('#PricePromotion').val(clearFormatNumber(pricePromotion));


        });
    });

</script>