Hotel/Hotel/ViewModels/HotelViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hotel.ViewModels
{
    public class HotelViewModel
    {
        public Guid RoomId { get; set; }
        public Guid HotelId { get; set; }
        public int? AvailableRoom { get; set; }
        public bool IsCancel { get; set; }
        public string HotelServiceType { get; set; }
        public string HotelConvenientTypeHotel { get; set; }
        public string RoomName { get; set; }
        public string HotelName { get; set; }
        public string Address { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public string ImageRoom { get; set; }
        public string Direction { get; set; }
        public string DirectionName { get; set; }
        public int? SingleBed { get; set; }
        public int? DoubleBed { get; set; }
        public int? MaxPeople { get; set; }
        public int? HotelRatingTypeId { get; set; }
        public string NumberStar { get; set; }
        public double PriceContract { get; set; }
        public double PricePromotion { get; set; }
        public double RoomArea { get; set; }
        //===Danh Gia===
        public string PointReview { get; set; }
        public string PointReviewText { get; set; }
        public int CountReview { get; set; }
        //!===Danh Gia===!
        public List<ConvenientTypeViewModel> ConvenientTypeList { get; set; }
    }

}

Hotel/Hotel/Areas/Admin/Controllers/HotelsController.cs
using Hotel.Models;
using Hotel.EntityFramework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hotel.Utilities;
using System.Data.Entity;
using Custom.Security;
using System.IO;
using System.Web.Mvc.Html;
using System.Net;
using System.Web.Script.Serialization;
using System.Xml.Linq;
using System.Web.Helpers;

namespace Hotel.Areas.Admin.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class HotelsController : BaseController
    {
        private readonly HotelEntities _db = new HotelEntities();
        private const string UploadFolderFile = "~/FileUploads/Image";
        int RecordsPerPage = 10;
        // GET: Admin/Hotels
        #region Khach san

        public ActionResult Index()
        {
            try
            {
                if (TempData["Notify"] != null)
                {
                    Notify notify = (Notify)TempData["Notify"];
                    ViewBag.Notify = notify;
                }

                ViewBag.CountryId = new SelectList(_db.tbl_Country.ToList(), "CountryId", "CountryName", null);

                ViewBag.HotelType = new SelectList(_db.tbl_HotelType.OrderBy(d => d.HotelTypeName).ToList(), "Id", "HotelTypeName", null);

                ViewBag.Status = new SelectList(XMLUtils.BindData("status"), "value", "text", null);

                var viewModel = new List<HotelViewModel>();
                return View(viewModel);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult GetHotelsList(string HotelName = "", string Address = "", int? HotelType = null, string Phone = "", int? CountryId = null, int? ProvinceId = null, int? DistrictId = null, int? Status = null)
        {
            //var hotels = _db.tbl_Hotel.Where(x => x.HotelName.ToLower().Contains(HotelName.ToLower()) 
            //&& Address == "" || x.Address.ToLower().Contains(Address.ToLower())
            //&& x.HotelTypeId == HotelType).ToList();
            var hotels = _db.tbl_Hotel.Where(x => x.IsDelete == false
            && (HotelName == "" || x.HotelName.ToLower().Contains(HotelName.ToLower()))
            && (Address == "" || x.Address.ToLower().Contains(Address.ToLower()))
            && (HotelType == null || x.HotelTypeId == HotelType)
            && (Phone == "" || x.Telephone == Phone)
            && (CountryId == null || x.CountryId == CountryId)
            && (ProvinceId == 0 || x.ProvinceId == ProvinceId)
            && (DistrictId == 0 || x.DistrictId == DistrictId)
            && (Status == null || x.IsActive == Status)
            ).ToList();
            var viewModel = hotels.Select(x => new HotelViewModel()
            {
                Id = x.Id,
                HotelName = x.HotelName,
                CountryId = x.CountryId,
                ProvinceId = x.ProvinceId,
                DistrictId = x.DistrictId,
                AreaId = x.AreaId,
                HotelRatingTypeId = x.HotelRatingTypeId,
                HotelTypeId = x.HotelTypeId,
                HotelConvenientType = x.HotelConvenientType,
                Address = x.Address,
                Telephone = x.Telephone,
                Mobile = x.Mobile,
                Longitude = x.Longitude,
                Latitude = x.Latitude,
                Content = x.Content,
                Email = x.Email,
                Url = x.Url,
                Image = x.Image,
                IsDelete = x.IsDelete,
                UserCreate = x.UserCreate,
                DateCreate = x.DateCreate,
                UserUpdate = x.UserUpdate,
                DateUpdate = x.DateUpdate
            }).ToList();

            foreach (var item in viewModel)
            {
                var country = _db.tbl_Country.FirstOrDefault(d => d.CountryId == item.CountryId);
                var province = _db.tbl_Province.FirstOrDefault(d => d.ProvinceId == item.ProvinceId);
                var district = _db.tbl_District.FirstOrDefault(d => d.DistrictId == item.DistrictId);

                if (country != null)
                    item.CountryName = country.CountryName;

                if (province != null)
                    item.ProvinceName = province.ProvinceName;

                if (district != null)
                    item.ProvinceName = district.DistrictName;
            }

            return PartialView("_HotelsList", viewModel);
        }

        public ActionResult GetRoomsListInEditHotel(Guid HotelId)
        {
            var rooms = _db.tbl_Room.Where(x => x.IsDelete == false
            && x.HotelId == HotelId
            ).ToList();
            var viewModel = rooms.Select(x => new RoomViewModel()
            {
                Id = x.Id,
                HotelId = x.HotelId,
                RoomName = x.RoomName,
                AvailableRoom = x.AvailableRoom,
                RoomArea = x.RoomArea,
                Direction = x.Direction,
                SingleBed = x.SingleBed,
                DoubleBed = x.DoubleBed,
                MaxPeople = x.MaxPeople,
                HotelConvenientType = x.HotelConvenientType,
                Image = x.Image,
                IsDelete = x.IsDelete,
                UserCreate = x.UserCreate,
                DateCreate = x.DateCreate,
                UserUpdate = x.UserUpdate,
                DateUpdate = x.DateUpdate
            }).ToList();

            //foreach (var item in viewModel)
            //{
            //    var hotel = _db.tbl_Hotel.FirstOrDefault(d => d.Id == item.HotelId);
            //    var direction = _db.tbl_Direction.FirstOrDefault(d => d.Id == item.Direction);


            //    if (hotel != null)
            //        item.HotelName = hotel.HotelName;

            //    if (direction != null)
            //        item.DirectionName = direction.DirectionName;
            //}

            return PartialView("_RoomList", viewModel);
        }

        public ActionResult GetHotelNoticesListInEditHotel(Guid HotelId)
        {
            var hotelNotices = _db.tbl_HotelNotice.Where(x => x.IsDelete == false
            && x.HotelId == HotelId
            ).ToList();
            var viewModel = hotelNotices.Select(x => new HotelNoticeViewModel()
            {
                Id = x.Id,
                HotelId = x.HotelId,
                Content = x.Content,
                IsDelete = x.IsDelete,
                UserCreate = x.UserCreate,
                DateCreate = x.DateCreate,
                UserUpdate = x.UserUpdate,
                DateUpdate = x.DateUpdate
            }).ToList();

            foreach (var item in viewModel)
            {
                var hotel = _db.tbl_Hotel.FirstOrDefault(d => d.Id == item.HotelId);

                if (hotel != null)
                    item.HotelName = hotel.HotelName;

            }

            return PartialView("_HotelNoticeList", viewModel);
        }

        public ActionResult GetHotelSurchargePolicysListInEditHotel(Guid HotelId)
        {
            var hotelSurcharges = _db.tbl_HotelSurchargePolicy.Where(x => x.IsDelete == false
            && x.HotelId == HotelId
            ).ToList();
            var viewModel = hotelSurcharges.Select(x => new HotelSurchargePolicyViewModel()
            {
                Id = x.Id,
                HotelId = x.HotelId,
                Condition = x.Condition,
                Amount = x.Amount,
                IsDelete = x.IsDelete,
                UserCreate = x.UserCreate,
                DateCreate = x.DateCreate,
                UserUpdate = x.UserUpdate,
                DateUpdate = x.DateUpdate
            }).ToList();

            foreach (var item in viewModel)
            {
                var hotel = _db.tbl_Hotel.FirstOrDefault(d => d.Id == item.HotelId);

                if (hotel != null)
                    item.HotelName = hotel.HotelName;

            }

            return PartialView("_HotelSurchargePolicyList", viewModel);
        }

        public ActionResult EditRoomPopup(Guid id)
        {
            var model = _db.tbl_Room.Where(x => x.Id == id).ToList();
            var viewModel = model.Select(s => new RoomViewModel()
            {
                Id = s.Id,
                HotelId = s.HotelId,
                RoomName = s.RoomName,
                AvailableRoom = s.AvailableRoom,
                RoomArea = s.RoomArea,
                Direction = s.Direction,
                SingleBed = s.SingleBed,
                DoubleBed = s.DoubleBed,
                MaxPeople = s.MaxPeople,
                HotelConvenientType = s.HotelConvenientType,
                Image = s.Image,
                IsDelete = s.IsDelete,
                UserCreate = s.UserCreate,
                DateCreate = s.DateCreate,
                UserUpdate = s.UserUpdate,
                DateUpdate = s.DateUpdate
            }).FirstOrDefault();

            //dll Hotel
            ViewBag.HotelId = new SelectList(
                    _db.tbl_Hotel.Where(d => d.IsDelete == false).OrderBy(d => d.HotelName).ToList(), "Id", "HotelName",
                    viewModel.HotelId);

            //ViewBag.HotelId = new SelectList(_db.tbl_Hotel.OrderBy(d => d.HotelName).ToList(), "Id", "HotelName", viewModel.HotelId); ;

            //dll Hướng
            ViewBag.DirectionType = new SelectList(_db.tbl_Direction.Where(x => x.IsDelete == false).OrderBy(x => x.DirectionName).ToList(), "Id", "DirectionName", viewModel.Direction);

            //dll Tien ich
            string[] convenientTypeIds = { };
            if (viewModel.HotelConvenientType != "" && viewModel.HotelConvenientType != null)
            {
                convenientTypeIds = viewModel.HotelConvenientType.Split(new char[] { ',' });
            }

            var sllConvenientType = new List<SelectListItem>();

Hotel/Hotel/Areas/Admin/Views/Hotels/Rooms.cshtml
@model IEnumerable<RoomViewModel>

@{
    ViewBag.Title = "Danh sách phòng";
}
<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            @using (Html.BeginForm("Rooms", "Hotels", FormMethod.Post, new { id = "form-search" }))
            {
                <div class="box-body">
                    <div class="row" style="padding: 0px;">
                        <div class="col-xs-12 col-md-3">
                            <div class="form-group">
                                <label>Khách sạn</label>
                                <div>
                                    @Html.DropDownList("HotelId", null, "---  Chọn  ---", new { @class = "form-control chosen-select input-sm" })
                                </div>
                            </div>
                        </div>
                       
                        <div class="col-xs-12 col-md-3">
                            <label>&nbsp;</label>
                            <div>
                                <button type="button" name="SubmitSearch" value="Search" id="btnTimKiem" class="btn btn-primary btn-sm"><i class="fa fa-search"></i>&nbsp;Tìm kiếm</button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Danh sách phòng</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="nContent">
                    <a href="@Url.Action("RoomsCreate")" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i>&nbsp;Thêm mới</a>
                    @Html.Partial("_RoomsList", Model)
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>

@section scripts{
    <script>
        $(function () {
            RoomModule.init();
        });

        var RoomModule = (function () {
            var danhSachRoomUrl = "/Admin/Hotels/GetRoomsList";

            function init() {
                initRoomTable();
            }

            $('#btnTimKiem').on('click', function (event) {
                initRoomTable();
            });

            function initRoomTable() {
                var hotelId = $('#HotelId').val();

                $.ajax({
                    type: "GET",
                    url: danhSachRoomUrl,
                    data: {
                        HotelId: hotelId,
                    },
                    success: function (response) {
                        $('#mytable').html(response);
                            $("#mytable").DataTable({
                            "paging": true,
                            "lengthChange": false,
                            "ordering": true,
                            "info": true,
                                "autoWidth": false,
                            destroy: true,
                            "aoColumnDefs": [
                                { 'bSortable': false, 'aTargets': [1] }
                            ]
                        });
                    }
                });
            }

            return {
                init: init,
                reloadRoomTable: initRoomTable
            };
        })();

        $(document).ready(function (event) {

        });

    </script>
}

Hotel/Hotel/Areas/Admin/Views/Hotels/RoomsEdit.cshtml
@model RoomViewModel
@{
    ViewBag.Title = "Thêm phòng";
}

<!-- cập nhật phòng -->
<div>
    @using (Html.BeginForm("RoomsEdit", "Hotels", FormMethod.Post, new { id = "form-submittour", enctype = "multipart/form-data", @class = "form-horizontal" }))
    {
        @Html.HiddenFor(m => m.Image)
        <div class="row tour">
            <div class="col-md-12 col-sm-12">
                <div class="box box-primary">
                    <div class="box-header with-border" data-widget="collapse">
                        <h3 class="box-title">Thông tin phòng</h3>
                    </div>
                    <div class="box-body" style="display: block;height:auto">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4">Khách sạn</label>
                                    <div class="col-md-8">
                                        @Html.DropDownListFor(m => m.HotelId, null, null, new { @class = "form-control chosen-select input-sm", @id = "editProvinceId" })
                                        @Html.ValidationMessageFor(model => model.HotelId)
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4">Tên phòng</label>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.RoomName, new { @class = "form-control input-sm" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4">Số lượng phòng</label>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.AvailableRoom, new { @class = "form-control input-sm" })

                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4">Diện tích</label>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.RoomArea, new { @class = "form-control input-sm" })

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-8 ">
                                <div class="form-group">
                                    <label class="col-md-2">Hướng</label>
                                    <div class="col-md-10">
                                        @*@Html.DropDownListFor(m => m.Direction, (SelectList)ViewBag.DirectionType, "-- Chọn --", new { @class = "form-control input-sm", @id = "ddlDirectionType" })*@
                                        <select name="sllDirectionTypeID" id="sllDirectionTypeID" class="form-control chosen-select" multiple="multiple">
                                            @foreach (var selectList in (List<SelectListItem>)ViewBag.ddlDirectionType)
                                            {
                                                <option value="@selectList.Value" @(selectList.Selected ? "selected" : "")>
                                                    @selectList.Text
                                                </option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 ">
                                <div class="form-group">
                                    <label class="col-md-2" style="width: 11%;">Tiện ích</label>
                                    <div class="col-md-10" style="width: 89%;">
                                        <select name="sllConvenientTypeID" id="sllConvenientTypeID" class="form-control chosen-select" multiple="multiple">
                                            @foreach (var selectList in (List<SelectListItem>)ViewBag.ddlConvenientType)
                                            {
                                                <option value="@selectList.Value" @(selectList.Selected ? "selected" : "")>
                                                    @selectList.Text
                                                </option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4">Số lượng gường đơn</label>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.SingleBed, new { @class = "form-control input-sm" })

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4">Số lượng gường đôi</label>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.DoubleBed, new { @class = "form-control input-sm" })

                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label class="col-md-4">Số người tối đa</label>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(m => m.MaxPeople, new { @class = "form-control input-sm" })

                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <label class="col-md-2" style="width: 11%;">Hình ảnh</label>
                                    <div class="col-md-4">
                                        @if (!String.IsNullOrEmpty(Model.Image))
                                        {
                                            <img src="~/FileUploads/Image/@Model.Image" height="150" width="150" />
                                        }
                                        else
                                        {
                                            <img src="~/FileUploads/Image/default-image.jpg" height="150" width="150" />
                                        }
                                        <input type="file" id="files" name="files" multiple="multiple" style="float: left; height: auto;" class="form-control" />
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 dropup f-left bar-footer">
                <button type="submit" class="btn btn-success btn-sm" id="btnSubmitRoom"><i class="fa fa-save"></i>&nbsp;Lưu</button>&nbsp;
                <a href="@Url.Action("Edit", new {  id=Model.HotelId  })" class="btn btn-danger btn-sm">
                    <i class="fa fa-reply"></i>&nbsp;Quay lại
                </a>
            </div>
        </div>
    }
    <div style="clear:both"></div>
</div>

@section scripts
{

}

Hotel/Hotel/Areas/Admin/Views/Hotels/_GetListImage.cshtml
@{
    var Lists = ViewBag.List as IEnumerable<tbl_ProductImage>;
}

<table id="myTableSlides" class="table table-striped jambo_table bulk_action table-bordered display-table">
    <thead>
        <tr class="table-header">
            <th class="column-title" style="display: table-cell;" width="40px">STT</th>
            <th class="column-title" style="display: table-cell;">Hình</th>
            <th class="column-title" style="display: table-cell;">Nhóm ảnh</th>
            <th class="column-title" style="display: table-cell;">Thứ tự</th>
            <th class="column-title no-link last" style="display: table-cell;">
                <span class="nobr"></span>
            </th>
        </tr>
    </thead>
    <tbody>
        @{ var STT = 1; }
        @foreach (var List in Lists)
        {
        <tr data-id="@List.Id" class="dg-hight clickable-row row-@List.Id" onclick="highlight_rowclick('row-@List.Id'); rowclick('row-@List.Id');">
            <td style="text-align: center;">
                @STT
            </td>
            <td style="text-align: center;">
                <img style="width:100px" src="~/FileUploads/Image/Hotels/@List.ImageUrl" />
            </td>
            <td style="text-align: center;">
                @Html.GetTextImageType(@List.Type) 
            </td>
            <td style="text-align: center;">
                @List.Order
            </td>
            <td class="last" style="text-align:center">
                <a style="cursor:pointer" class="itemDelete" onclick="DeleteImage('@List.Id')">Xóa</a>
            </td>
        </tr>

            STT++;
        }
    </tbody>
</table>

Hotel/Hotel/Areas/Admin/Views/Hotels/_HotelNoticeList.cshtml
@model IEnumerable<HotelNoticeViewModel>

@{
    ViewBag.Title = "Danh lưu ý khách sạn";
    var ordId = 1;
}

<table id="mytableHotelNotice" class="table table-bordered table-striped">
    <thead>
        <tr style="background-color: #1b80c8; color: white; font-size: 11.5px">
            <th style="width:40px;min-width:40px">
                STT
            </th>
            <th>
                Nội dung
            </th>
            <th style="width:70px;min-width:70px">
            </th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr id="row_@item.Id">
            <td class="text-center">
                @(ordId++)
            </td>
            <td class="text-left">
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td class="tt-wrapper text-center">
                <a href="javascript:DoEditNotice('@item.Id')" class="text-success" data-original-title="Cập nhật" title="Cập nhật">
                    <span> Cập nhật </span>
                    <i class="fa fa-edit fa-lg"></i>
                </a>&nbsp;
                <span> | </span>
                <a href="javascript:DoDeleteNotice('@item.Id')" class="text-danger delete" data-original-title="Xóa" title="Xóa">
                    <span> Xoá </span>
                    <i class="fa fa-trash-o fa-lg"></i>
                </a>
            </td>
        </tr>

    }
</table>

Hotel/Hotel/Areas/Admin/Views/Hotels/_HotelNoticesEdit.cshtml
@model tbl_HotelNotice

@using (Html.BeginForm("HotelNoticesEdit", "Hotels", FormMethod.Post, new { id = "frmPopEditNotice" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.Id)
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="title-modal">Cập nhật lưu ý khách sạn</span>
    </div>
    <div class="modal-body form-horizontal">
        <div class="row">
            @Html.HiddenFor(m => m.HotelId, new { @id = "idHotelPopupEditNotice" })
            <div class="col-md-12 mg-top5">
                <div class="form-group">
                    <label class="col-sm-2 control-label">
                        Nội dung
                    </label>
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control", @id = "inputTextChange" } })
                        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="modal-footer">
        <div class="text-left">
            <button type="button" id="btnEditNotice" onclick="mySubmitEditNotice()" data-dismiss="modal" class="btn btn-success btn-sm"><i class="fa fa-save"></i>&nbsp;Lưu</button>
            <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Quay lại</button>
        </div>
    </div>
}

Hotel/Hotel/Areas/Admin/Views/Hotels/_HotelSurchargePolicyList.cshtml
@model IEnumerable<HotelSurchargePolicyViewModel>

@{
    ViewBag.Title = "Danh sách phòng";
    var ordId = 1;
}

<table id="mytableSurcharge" class="table table-bordered table-striped">
    <thead>
        <tr style="background-color: #1b80c8; color: white; font-size: 11.5px">
            <th style="width:5%;">
                STT
            </th>
            <th>
                Điều kiện
            </th>
            <th>
                Giá phụ thu
            </th>
            <th width="15%" style="min-width:40px;"></th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr id="row_@item.Id">
            <td class="text-center">
                @(ordId++)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Condition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td class="tt-wrapper text-center">
                <a href="javascript:DoEditSur('@item.Id')" class="text-success" data-original-title="Cập nhật" title="Cập nhật">
                    <span> Cập nhật </span>
                    <i class="fa fa-edit fa-lg"></i>
                </a>&nbsp;
                <span> | </span>
                <a href="javascript:DoDeleteSurcharge('@item.Id')" class="text-danger delete" data-original-title="Xóa" title="Xóa">
                    <span> Xoá </span>
                    <i class="fa fa-trash-o fa-lg"></i>
                </a>
            </td>
        </tr>

    }
</table>